### ISSUE TITLE
Remove "Dublin Core" from collection/show pages

### ISSUE THREAD

**Issue by lisagoff** [scholarslab/takeback#29]

**Comment by jeremyboggs** [comment]
@lisagoff This shouldn't be displaying on item pages. I don't see it on [Item 582](http://takeback.scholarslab.org/items/show/582) for example. If you do it somewhere, can you share a link?

**Comment by lisagoff** [comment]
Here's an example: http://takeback.neatline-uva.org/collections/show/11
-Lisa

**Comment by jeremyboggs** [comment]
A specific task for the more general #25.

**Comment by jeremyboggs** [comment]
This was fixed in 9659994.
