### ISSUE TITLE
Collection 15 years seem wrong

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/takeback#41]
There's a PHP warning that is preventing the 'Years' summary to be displayed. Let's investigate to see if this is a data issue or a programming issue.

**Comment by emily-em** [comment]
Other date stuff: 
- In Women’s Center archive collection, “Students discuss causes of date rape at forum” date is wrong.
- 2015 Take Back the Night poster is labeled as 1917

**Comment by emily-em** [comment]
In Rolling Stone Aftermath, something is wrong in the year range in summary statistics
