### ISSUE TITLE
Splash page blurb redundancy

### ISSUE THREAD

**Issue by emily-em** [scholarslab/takeback#42]
The text of the blurb within the image is repeated verbatim at the top of the larger blurb below
Possible Solutions:
Eliminate repeated part and leave the rest alone
Put all of the text in the blurb above
Put all of the text below and make image smaller

(currently the two blurbs are not showing on live version of the site, but I successfully restored them to my local version)

**Comment by jeremyboggs** [comment]
fixed in database on site.
